import { AccountTypeEnum } from '@common/enums/account-type.enum';
import type { SelectOptionResponse } from '../interfaces/select-option.response';

export const ACCOUNT_TYPE_OPTIONS: SelectOptionResponse[] = [
  { value: AccountTypeEnum.CRYPTO, label: 'Crypto' },
  { value: AccountTypeEnum.FOREX, label: 'Forex' },
  { value: AccountTypeEnum.STOCKS, label: 'Stock' },
];

export const CURRENCY_OPTIONS: SelectOptionResponse[] = [
  { value: 'USD', label: 'US Dollar (USD)' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { value: 'EUR', label: 'Euro (EUR)' },
  { value: 'GBP', label: 'British Pound (GBP)' },
  { value: 'JPY', label: 'Japanese Yen (JPY)' },
  { value: 'AUD', label: 'Australian Dollar (AUD)' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)' },
  { value: 'CHF', label: 'Swiss Franc (CHF)' },
  { value: 'CNY', label: 'Chinese Yuan (CNY)' },
  { value: 'SGD', label: 'Singapore Dollar (SGD)' },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { value: 'KRW', label: 'South Korean Won (KRW)' },
  { value: 'INR', label: 'Indian Rupee (INR)' },
  { value: 'THB', label: 'Thai Baht (THB)' },
  { value: 'PHP', label: 'Philippine Peso (PHP)' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { value: 'VND', label: 'Vietnamese Dong (VND)' },
  { value: 'BRL', label: 'Brazilian Real (BRL)' },
  { value: 'MXN', label: 'Mexican Peso (MXN)' },
  { value: 'ZAR', label: 'South African Rand (ZAR)' },
  { value: 'AED', label: 'UAE Dirham (AED)' },
  { value: 'SAR', label: 'Saudi Riyal (SAR)' },
  { value: 'TRY', label: 'Turkish Lira (TRY)' },
  { value: 'PLN', label: 'Polish Zloty (PLN)' },
  { value: 'SEK', label: 'Swedish Krona (SEK)' },
  { value: 'NOK', label: 'Norwegian Krone (NOK)' },
  { value: 'DKK', label: 'Danish Krone (DKK)' },
  { value: 'RUB', label: 'Russian Ruble (RUB)' },
  { value: 'USDT', label: 'Tether (USDT)' },
  { value: 'USDC', label: 'USD Coin (USDC)' },
  { value: 'BTC', label: 'Bitcoin (BTC)' },
  { value: 'ETH', label: 'Ethereum (ETH)' },
];

export const BROKER_OPTIONS: SelectOptionResponse[] = [
  { value: 'binance', label: 'Binance' },
  { value: 'bybit', label: 'Bybit' },
  { value: 'okx', label: 'OKX' },
  { value: 'coinbase', label: 'Coinbase' },
  { value: 'kraken', label: 'Kraken' },
  { value: 'kucoin', label: 'KuCoin' },
  { value: 'bitget', label: 'Bitget' },
  { value: 'gate-io', label: 'Gate.io' },
  { value: 'indodax', label: 'Indodax' },
  { value: 'tokocrypto', label: 'Tokocrypto' },
  { value: 'pintu', label: 'Pintu' },
  { value: 'reku', label: 'Reku' },
  { value: 'oanda', label: 'OANDA' },
  { value: 'ic-markets', label: 'IC Markets' },
  { value: 'pepperstone', label: 'Pepperstone' },
  { value: 'xm', label: 'XM' },
  { value: 'forex-com', label: 'Forex.com' },
  { value: 'fxcm', label: 'FXCM' },
  { value: 'exness', label: 'Exness' },
  { value: 'interactive-brokers', label: 'Interactive Brokers' },
  { value: 'charles-schwab', label: 'Charles Schwab' },
  { value: 'fidelity', label: 'Fidelity' },
  { value: 'robinhood', label: 'Robinhood' },
  { value: 'etrade', label: 'E*TRADE' },
  { value: 'td-ameritrade', label: 'TD Ameritrade' },
  { value: 'webull', label: 'Webull' },
  { value: 'tastytrade', label: 'tastytrade' },
  { value: 'moomoo', label: 'moomoo' },
  { value: 'stockbit', label: 'Stockbit' },
  { value: 'ajaib', label: 'Ajaib' },
  { value: 'mirae-asset-indonesia', label: 'Mirae Asset Sekuritas Indonesia' },
  { value: 'mandiri-sekuritas', label: 'Mandiri Sekuritas' },
  { value: 'bca-sekuritas', label: 'BCA Sekuritas' },
  { value: 'pluang', label: 'Pluang' },
  { value: 'other', label: 'Other' },
];

export const TIMEZONE_OPTIONS: SelectOptionResponse[] = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta (WIB, Indonesia)' },
  { value: 'Asia/Makassar', label: 'Asia/Makassar (WITA, Indonesia)' },
  { value: 'Asia/Jayapura', label: 'Asia/Jayapura (WIT, Indonesia)' },
  { value: 'America/New_York', label: 'America/New_York (US Eastern)' },
  { value: 'America/Chicago', label: 'America/Chicago (US Central)' },
  { value: 'America/Denver', label: 'America/Denver (US Mountain)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (US Pacific)' },
  { value: 'America/Phoenix', label: 'America/Phoenix (US Arizona)' },
  { value: 'America/Anchorage', label: 'America/Anchorage (US Alaska)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (US Hawaii)' },
  { value: 'Europe/London', label: 'Europe/London (GMT/BST)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET/CEST)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (CET/CEST)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (MSK)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (HKT)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (KST)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (GST)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (ICT)' },
  { value: 'Asia/Manila', label: 'Asia/Manila (PHT)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEST/AEDT)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (AEST/AEDT)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZST/NZDT)' },
  { value: 'America/Toronto', label: 'America/Toronto (Canada Eastern)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (Canada Pacific)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (BRT)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST)' },
];
